### ISSUE TITLE
Regression checks for HTTP Block logging and metadata changes branch

### ISSUE THREAD

**Issue by lukestanley** [kendraio/kendraio-app#553]
🔍 For the [http-block-aws-signed-authentication-main-with-logs](https://github.com/kendraio/kendraio-app/pull/538) branch, we need to check that it doesn’t cause regressions for existing, non-Freecord’s related Flows.
This is to serve the parent issue #554

🚦 This should let us unblock the PR and investigate any reactivity issues around file-bucket use separately

📋 This issue is to list and track what’s tested, the results, and aggregate an overview below.

##  🧪 Testing overview

**Suggested format:**
What Flow sections, for who is testing it, what the result was, Interpretation of if overall it is good or bad, and if it is a regression or not.

| Flow ({adapter name} / {flow ID})  | Tester | Result | Interpretation|
| ------------------------------------ | ------------------------- | --------------- | ----------------- |
|[E.g: freecords/dashboard]                   |            | Concise result: [✅Working]/[❌Failures]               | [👍/👎] [Implications, safe to merge?]|
|...                  |            | Concise result: [✅Working]/[❌Failures]               | [👍/👎] [Implications, safe to merge?]|

**Comment by gsambrotta** [comment]
@lukestanley do you mean to use the above table in this way?
And we all fill in info in this table, right? Or every person create a comment with their own table?

I am not so sure what is the meaning of the Test resul and Interpretation col. 
**Test result**: Do you mean unit/e2e tests? Or the result of our QA test? Am I suppose to put just a ✅ or a ❌ or several of them? If several what they are rapresenting?

**Interpretation**: Do you mean what we, as QA, think is the outcome of the test? 



| 🤝 Flow adapter / Showcase / Partner | 🔢 Flow ID | 🧑‍💻 Tester(s) | ✅/❌ Test result | 🧐 Interpretation 👍/👎 |
| ------------------------------------ | ---------- | --------------- | --------------- | ----------------- |
|     Adapter: contributions <img width="778" height="457" alt="Image" src="https://github.com/user-attachments/assets/c4e67865-2f49-4305-b8f9-888aebf979b3" />           |  contributors  |     Gio       | ✅              | 👍     |
|                 |    |            | ✅✅/❌❌               | 👍/👎        |

**Comment by CodeKrakken** [comment]
🐛 Problem
[Freecords](https://kendraio-n92bry9ut-kendraio.vercel.app/freecords/getsongshashverify) - Add to Backblaze button does not fully execute. Currently, it GETs and PUTs metadata and an image.

🎯 Goal
It should GET metadata, an image and an audio file from their respective locations and PUT them into the Freecords Backblaze bucket.

📋 Requirements

After the Add to Backblaze button is pushed, the Freecords Backblaze bucket should contain:

- [ ] Metadata (.xml)
- [ ] Audio (.wav)
- [ ] Image (.jpg)

-----------------------------------------------------------------------------------------------------------------------------------------------------------

🐛 Problem
[Task](https://kendraio-n92bry9ut-kendraio.vercel.app/task/dashboard) - Issues and comments from

🎯 Goal


📋 Requirements

After the Add to Backblaze button is pushed, the Freecords Backblaze bucket should contain:

 Metadata (.xml)
 Audio (.wav)
 Image (.jpg)

-----------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by dahacouk** [comment]
@lukestanley why have the heading "Flow adapter / Showcase / Partner" when I think it should just be "Flow adapter" for accuracy and identification? Or why not just put the URL part "Flow adapter/id"? Why would we never want both together?

In terms of the headers I don't think the emojis add anything but distraction.

In the test results having multiple crosses and ticks looks really confusing. Should the be only one thing? Pass or fail?

**Comment by lukestanley** [comment]
@gsambrotta @CodeKrakken @dahacouk 
I have simplified the changes for the File Input Block, it now:
- Only warns if debug mode is enabled, reverting HTML template changes.
- A few added MIME types that are used,

It keeps UI, outputs, and behaviour the same as main branch to avoid reactivity issues.
It's difference from main is now much more reduced!

**Comment by lukestanley** [comment]
@CodeKrakken 
Since it's a different set of manual testing, do it as a new comment.

I've also noticed a reason for the flakey grid test and fixed the test, and now it is green!

**Comment by CodeKrakken** [comment]
Latest manual testing results:

| Flow  |   Tester |  Test result |  Interpretation  |
| ------------------------------------ | --------------- | --------------- | ----------------- |
|    freecords/dashboard  |    Donald       | ✅ List songs<br>✅ See details<br>❌ Add to Backblaze<br>✅ Verify<br>✅ Retry add              | 👎     |
|   bandsintown/listEvents |    Donald        | ❌ List events             | 👎        |
|   bandsintown/addEvent |    Donald        | ✅ Find artist <br>❌ Find venue <br>❌ Upload event              | 👎        |
|   bandsintown/editEvent |    Donald        | ✅ Find artist <br>❌ Find venue <br>❌ Upload event             | 👎        |
|   domains/doubleDynadotDomains |    Donald        | ✅ Use first key<br>✅ Use second key               | 👍        |
|   subscribe/list |    Donald        | ✅ Display list               | 👍       |
|    task/dashboard   |    Donald        | ✅ Display Google Drive Comments<br>✅ Display GitHub Issues<br>✅ Display Linear Issues             | 👍        |

**Comment by lukestanley** [comment]
@CodeKrakken 
Please can you add more detail on what is failing to the `Test result` column, and an interpretation of why you think the result means it should or should not be merged in the `Interpretation` column?
Please consider what someone looking at it will wonder.
What is going wrong when adding to Backblaze?
How do they compare to main?
What changed with how the task dashboard displays Linear issues?

**Comment by lukestanley** [comment]
It turns out that https://app.kendra.io/demo/corsExampleDirect was enough help reveal the error.
https://kendraio-9e058ubbq-kendraio.vercel.app/demo/corsExampleDirect <-- this older version has an error
https://kendraio-j2xk1en6h-kendraio.vercel.app/demo/corsExampleDirect <-- I have fixed an error here!

**Comment by gsambrotta** [comment]
Thank you @lukestanley. Here is my last test on the branch https://kendraio-j2xk1en6h-kendraio.vercel.app/demo/corsExampleDirect

Most of the issue got solved. Just CultureBanked seems to struggle with change to a big Flow with nested Flows


| Flow ({adapter name} / {flow ID})  | Tester| Result | Interpretation|
| ------------------------------------ | --------------- | --------------- | ----------------- |
|  contributions/contributors | Gio |  ✅ Show data on page load <br> ✅ Show data on reload icon <br> ❌ Delete data on "delete" button (it needs a page reload)    | 👍 same issue as production when delete item: It needs a page reload to not see the item on the page anymore|
| contributions/contributors-add  | Gio | ✅ Add Item to DB <br> ✅ Item added to items list | 👍 New item added to DB and Flow, flow prevent empty HTTP to be submitted. Tested adding several items |
| contributions/contributors-edit-record | Gio | ✅ Edit Record  | 👍 | 
| contributions/projects | Gio |   ✅ Show data on page load <br> ✅  Show data on reload icon <br> ❌ Delete data on "delete" button (it needs a page reload)   |👍 same issue as production when delete item: It needs a page reload to not see the item on the page anymore | 
| contributions/project-edit-record | Gio | ✅ Edit Record  | 👍 | 
| contributions/contributors-add | Gio | ✅ Add Record | 👍 | 
| contributions/contributions | Gio |  ✅ Show data on page load <br> ✅ Show data on reload icon <br> ❌ Delete data on "delete" button (it needs a page reload)  | 👍  same issue as production when delete item: It needs a page reload to not see the item on the page anymore  | 
| contributions/contributions-add| Gio | ✅  Add Item | 👍 | 
| contributions/contributions-edit-record | Gio | ✅ Edit Item  | 👍 |
| fireflies/listMeetings | Gio | ✅  List Meetings | 👍 |
|fireflies/viewMeeting | Gio | ❌ View Meeting data  | 👎 Audio not playing. CORS error and error TypeError: Failed to fetch the mp3 | 
| /kendraio/audioClip | Gio | ✅ Upload Audio <br> ✅ Play Audio | 👍 | 
| kendraio/kendraioEmployees | Gio |  ✅ Show data on page load <br> ✅  Show data on reload icon | 👍 | 
| harvest/timesheet | Gio | ✅ Show Timesheets  | 👍 | 
| harvest/timesheetDetail | Gio | ✅ Show Timesheet Detail | 👍 Not showing any data as it happen in production | 
| /culturebanked/artist2Database | Gio | ✅ Show Data on first load <br> ❌ sometime not show all data on reload or after editing an art work | 👎 | 
|/culturebanked/artist2EditWork?id=5 | Gio | ✅ Show Data on first load <br> ❌ Taking long to load nested section on second time user land here after click "Edit" in previous Flow <br> ❌ Not showing nested or edited section after the second time the user land here after clicking "Edit" from /artist2Database <br>  ✅  showing nested or edited section after the second time the user land here after clicking "Edit" from /artist2Assets| 👎 | 
|culturebanked/artist2EditBeneficiaries?id=16 | Gio | ✅ Show Data on first load <br> ✅ show correct edited data even after back-and-edit-again | 👍 | 
|/murmurations/loadSchema | Gio | ❌ Cannot be test as json.stringify is not deployed yet| -- | 
|/murmurations/indexExplorer | Gio | ✅ Show Data on first load <br> ✅ Filter and show correct data on search | 👍 |
|/teosto/unidentifiedWorksImportFile | Gio | ✅ Correctly import a JSON File | 👍 |  
|/teosto/unidentifiedWorksList | Gio | ✅ Show Data on first load <br> ✅ Select data and show selected item in table <br> ✅ Add comment and show in a message | 👍 |

**Comment by CodeKrakken** [comment]
@dahacouk @lukestanley Unfortunately removing the gosubs has not fixed the issue! I've looked into a bit though. 

Putting the audio ahead of the image simply makes the audio work and the image fail. So it isn't to do with the specific blocks.

However, removing the metadata blocks gives an interesting result, as it causes the audio and image blocks to execute simultaneously, rather than sequentially. So that might be food for thought.

**Comment by lukestanley** [comment]
@CodeKrakken @dahacouk 
 I have my double image get and BPUT requests working just fine, and I have debug turned on and I am using an init block and `"skipInit": false`.

| Flow  |   Tester |  Test result |  Interpretation  |
| ------------------------------------ | --------------- | --------------- | ----------------- |
| freecords/imagedoublesj2Xk1En6H |    Luke        | ✅ Able to GET and BPUT icons: 72x72, and 96x96 to B2 bucket and back with hash matching and debug info shown  | 👍       |

https://kendraio-j2xk1en6h-kendraio.vercel.app/freecords/imagedoublesj2Xk1En6H

<img width="1922" height="1237" alt="Image" src="https://github.com/user-attachments/assets/65bb206d-c2c6-41f9-b254-30a5e00dcd5f" />

<img width="1922" height="1237" alt="Image" src="https://github.com/user-attachments/assets/adfdee3c-7141-4f49-a03c-b7227ffa8391" />

Minimal version of the Flow code:
```json
{
  "title": "Double image upload test",
  "blocks": [
    {
      "type": "init"
    },
    {
      "type": "variable-get",
      "name": "freecords"
    },
    {
      "type": "context-save",
      "key": "api"
    },
    {
      "type": "http",
      "method": "GET",
      "endpoint": "/assets/icons/icon-72x72.png",
      "responseType": "arraybuffer",
      "skipInit": false,
      "storeMetadataInContext": true,
      "blockComment": "Load local 72x72 icon"
    },
    {
      "type": "mapping",
      "mapping": "{ content: data }",
      "blockComment": "Map fetched bytes to content for upload"
    },
    {
      "type": "http",
      "method": "BPUT",
      "endpoint": "https://freecords.s3.eu-central-003.backblazeb2.com/icon-72x72.png",
      "useProxy": true,
      "authentication": {
        "type": "aws-sigv4",
        "secretKeyGetter": "context.api.secretKey",
        "accessKeyIdGetter": "context.api.accessKeyId"
      },
      "skipInit": false,
      "headers": {
        "Content-Type": "'image/png'"
      },
      "storeMetadataInContext": false,
      "blockComment": "Upload 72x72 icon to freecords"
    },
    {
      "type": "http",
      "method": "GET",
      "endpoint": "https://freecords.s3.eu-central-003.backblazeb2.com/icon-72x72.png",
      "useProxy": true,
      "responseType": "arraybuffer",
      "authentication": {
        "type": "aws-sigv4",
        "secretKeyGetter": "context.api.secretKey",
        "accessKeyIdGetter": "context.api.accessKeyId"
      },
      "skipInit": false,
      "storeMetadataInContext": true,
      "blockComment": "Verify 72x72 icon from freecords"
    },
    {
      "type": "http",
      "method": "GET",
      "endpoint": "/assets/icons/icon-96x96.png",
      "responseType": "arraybuffer",
      "skipInit": false,
      "storeMetadataInContext": true,
      "blockComment": "Load local 96x96 icon"
    },
    {
      "type": "mapping",
      "mapping": "{ content: data }",
      "blockComment": "Map fetched bytes to content for upload"
    },
    {
      "type": "http",
      "method": "BPUT",
      "endpoint": "https://freecords.s3.eu-central-003.backblazeb2.com/icon-96x96.png",
      "useProxy": true,
      "authentication": {
        "type": "aws-sigv4",
        "secretKeyGetter": "context.api.secretKey",
        "accessKeyIdGetter": "context.api.accessKeyId"
      },
      "skipInit": false,
      "headers": {
        "Content-Type": "'image/png'"
      },
      "storeMetadataInContext": false,
      "blockComment": "Upload 96x96 icon to freecords"
    },
    {
      "type": "http",
      "method": "GET",
      "endpoint": "https://freecords.s3.eu-central-003.backblazeb2.com/icon-96x96.png",
      "useProxy": true,
      "responseType": "arraybuffer",
      "authentication": {
        "type": "aws-sigv4",
        "secretKeyGetter": "context.api.secretKey",
        "accessKeyIdGetter": "context.api.accessKeyId"
      },
      "skipInit": false,
      "storeMetadataInContext": true,
      "blockComment": "Verify 96x96 icon from freecords"
    }
  ],
  "id": "imagedoublesminimalj2Xk1En6H",
  "adapterName": "freecords"
}
```

<img width="1922" height="1237" alt="Image" src="https://github.com/user-attachments/assets/ee6f248d-3337-48e4-b1c2-9747aa9daf78" />

Donald, presumably there is a difference your flows have that is breaking them?
I will add a third image get and BPUT to check third time is good too. Lucky we have so many icon resolutions!

**Comment by lukestanley** [comment]
@CodeKrakken @dahacouk 
The simple test is working fine with **3 different images** too:

https://kendraio-j2xk1en6h-kendraio.vercel.app/freecords/imagetriplej2Xk1En6H
<img width="1922" height="1302" alt="Image" src="https://github.com/user-attachments/assets/f0e5d5af-5ce7-48b3-8cdc-16dd28bb6b3e" />

What the Flow does to upload three PNG icons (72×72, 96×96, 128×128) from the local app assets, to the **freecords** Backblaze B2 S3 bucket, and then **verifies** each upload by reading it back, showing us the hash is as expected. (2be88ca4242c76e8253ac62474851065032d6833 is the common empty response hash when doing the BPUT.)


* **init** I used the init block which is still a bit of mystery to me, but it works with it.
* 🔐 **variable-get "freecords"** loads saved credentials. and saves to context under "api"**
### 2) For each icon size (72, 96, 128) 🖼️

For **72×72**, then **96×96**, then **128×128**, the same three-step pattern runs:

1. **Load local file**
   `GET /assets/icons/icon-<size>.png` as raw bytes with `arraybuffer`, and saves metadata to context.

2. **mapping** sets `{ content: data }` so the bucket BPUT request has content in the expected format to upload it as bytes.

3. **Upload to bucket**
   **BPUT** to `https://freecords.s3.eu-central-003.backblazeb2.com/icon-<size>.png` with header `Content-Type: 'image/png'`.
   `useProxy: true`, it uses our CORS proxy. Upload blocks don’t store metadata in context.

4. **Verify**
   **GET** the just-uploaded `icon-<size>.png` from the **freecords** bucket to confirm it’s retrievable.
* `storeMetadataInContext` is **true** on reads for checking the hash and status.
* All bucket requests go through the proxy (`useProxy: true`).
Donald, can you think of anything your flows are doing differently?

**Comment by lukestanley** [comment]
@CodeKrakken 
```
 I've finished manually testing my Flows and I'm pleased to confirm that everything is working as it should. So as long as @gsambrotta is also happy, there's no reason not to merge the pull request in my view.
```
Please could something like those last 2 lines [go on the Pull Request itself](https://github.com/kendraio/kendraio-app/pull/538) so we can it merge it soon?
https://github.com/kendraio/kendraio-app/pull/538
